JqUiMvc/Controllers/AgendaController.cs
using JqUiMvc.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JqUiMvc.Controllers
{
    public class AgendaController : Controller
    {
        //
        // GET: /Agenda/
        public ActionResult Index()
        {
            var siteID = Repository.DefaultSiteID;

            Repository.VisitModel = new VisitModel
            {
                VisitID = 99,
                VisitName = "Visit Agenda",
                VisitTypeID = Repository.GetVisitTypes(siteID).First().ID,
                SiteID = siteID,
                //IsOffSite = vm.IsOffSite,
                StartDate = DateTime.Parse("2014-07-28 08:00"),
                EndDate = DateTime.Parse("2014-07-28 14:00"),
            };

            Repository.VisitModel.Agenda = new VisitAgendaModel();

            //var agIt = new AgendaItem
            //{
            //    Room = Repository.GetRooms().Where(r=>r.SiteID == siteID).First(),
            //    Start = Repository.VisitModel.StartDate,
            //    End = Repository.VisitModel.EndDate,
            //};

            //Repository.VisitModel.Agenda.Items.Add(agIt);

            ViewBag.AgendaCats = Repository.GetAgendaTopicCategories();
            ViewBag.Rooms = Repository.GetRooms().Where(r => r.SiteID == siteID);

            return View(Repository.VisitModel);
        }
        [HttpGet]
        public ActionResult GetRoom(int roomID)
        {
            var room = Repository.GetRooms().Where(r => r.ID == roomID).Single();

            return PartialView("_AgendaRoom", room);
        }
        [HttpGet]
        public ActionResult GetAgendaItem(int topicID, string instanceID)
        {
            var agIt = new AgendaItem
            {
                ID = topicID,
                Name = "TODO: Name for #" + topicID.ToString(),
                InstanceID = instanceID
            };

            //var room = Repository.GetRooms().Where(r => r.ID == roomID).Single();

            return PartialView("_AgendaItem", agIt);
        }
	}
}

JqUiMvc/Views/Agenda/Index.cshtml
@model JqUiMvc.Data.VisitModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutJustScripts.cshtml";
}
@section Styles{
    <style>
        /* IE has layout issues when sorting (see #5413) */
        .group {
            zoom: 1;
        }
        .agendaPalette {
            /*position: relative;*/
            width: 300px;
            float: left;
            /*height: 200px;*/
            /*display: inline;*/
        }
        .beAgendaDayToolbar {
            border: solid 1px black;
        }
        .agendaDay {
            /*width: 400px;*/
            /*width: 100%;*/
            height: 100%;
            min-height: 100px;
            float: left;
            /*margin-top: 1em;*/
            margin-left: 1em;
            display: inline;
            border: solid 1px black;
            overflow:auto;
        }
        .beAgendaRoom {
            width: 400px;
            margin-left: 0.5em;
            display: inline;
            float: left;
            border: solid 1px black;
        }
        /* style the list to maximize the droppable hitarea */
        #day1 ol {
            margin: 0;
            padding: 0; /*1em 0 1em 3em;*/
        }

        #button {
            padding: .5em 1em;
            text-decoration: none;
        }

        #effect {
            position: relative;
            /*width: 240px;
        height: 135px;
        padding: 0.4em;*/
        }
    </style>
}
<h2>Agenda</h2>
<div class="container">
    @*<div class="CCCrow">*@
    <button id="button" class="ui-state-default ui-corner-all">Show</button>
    <div class="Xcol-md-12">
        <div class="agendaPalette ">
            <input type="radio" title="Ripple" />Topics
            <input type="radio" title="Fixed" />Meals
            @*<div id="effect" class="ui-widget-content ui-corner-all">*@
            <div id="agendaCategories">
                @foreach (var cat in ViewBag.AgendaCats)
                {
                    <h2>@cat.Name</h2>
                    <div>
                        <ul class="list-group">
                            @foreach ( var top in cat.Items)
                            {
                                <li class="list-group-item" data-id="@top.ID">@top.Name</li>
                            }
                        </ul>
                    </div>
                }
                <h2><a href="#">Public Sector MCB</a></h2>
                <div>
                    <ul class="list-group">
                        <li class="list-group-item" data-id="1">Federal Government Overview</li>
                        <li class="list-group-item" data-id="3">Lenovo Education Strategy</li>
                        <li class="list-group-item" data-id="5">Vista / One Note</li>
                    </ul>
                </div>
                <h2><a href="#">Corporate Information</a></h2>
                <div>
                    <ul class="list-group">
                        <li class="list-group-item" data-id="2">''Prepping for Showtime''- How to Get the Most Out of Your Customer Visit</li>
                        <li class="list-group-item" data-id="4">A Secondlife Virtual Briefing Center</li>
                        <li class="list-group-item" data-id="6">An Event at Chicago's Museum of Science & Industry</li>
                    </ul>
                </div>
                <h2><a href="#">Management Overview</a></h2>
                <div>
                    <ul class="list-group">
                        <li class="list-group-item" data-id="7">Arrival (15 min)</li>
                        <li class="list-group-item" data-id="8">Next Steps (10 min)</li>
                        <li class="list-group-item" data-id="9">Sit-down Lunch (60 min)</li>
                    </ul>
                </div>
            </div>
            @*</div>*@
        </div>

        <div id="day1" class="agendaDay">
            <h3 class="ui-widget-header">Day 1</h3>
            <div class="beAgendaDayToolbar">
                <button id="addRoom">+ Room</button>
                @*<input type="button" title="+ Room">+ Room</input>*@
                <b>Time:</b>
                <input type="radio" title="Ripple" />Ripple
                <input type="radio" title="Fixed" />Fixed
                <b>View:</b>
                <input type="radio" title="Ripple" />List
                <input type="radio" title="Fixed" />Time
            </div>
            <div class="beAgendaRooms" id="beAgendaRooms">
                
            </div>
        </div>
    </div>
    @*</div>*@
</div>
@section Scripts{
    <script>
        AgendaItem = function (item) {
            var name = item.text();
            var droppedID = item.data('id');
            var uniqDivId = new Date().getTime(); // milliseconds since 1970

            var ai =$('<div/>', { class: 'group', id: uniqDivId })
                    .append($('<div/>', { class: 'myHead', text: name }))
                    .append($('<div/>', { text: droppedID }));

            return ai;
        }

        function addAgendaItem(container,item) {
            //var ai = AgendaItem(item);
            var name = item.text();
            var droppedID = item.data('id');
            var uniqDivId = new Date().getTime(); // milliseconds since 1970

            var values =
                {
                    "topicID": droppedID,
                    "instanceID": uniqDivId
                };

            var ai = $('<div/>', { class: 'group', id: uniqDivId })
                    .append($('<div/>', { class: 'myHead', text: name }))
                    .append($('<div/>', { text: droppedID }));

            $(container).append(ai);

            $.get("@Url.Action("GetAgendaItem")", values, function (data, textStatus, jqXHR) {
                var d = uniqDivId;
                var v = values;
                //$('#' + uniqDivId).append(data);//.html(data);
                ai.replaceWith(data);

                //$(this).parent(".beAgendaRoom").accordion('refresh');
                //ai.parent(".beAgendaRoom").accordion('refresh');
                $(this).parent(".beAgendaRoom").accordion('refresh');
            })
            @*var url = '@Url.Action("GetAgendaItem", "Agenda", new { topicID = -1, instanceID = -2 })';//?topicID=' + droppedID;// + '&instanceID=' + uniqDivId;
            url = url.replace("-1", droppedID).replace("-2", uniqDivId);*@
            @*var url = "@Url.Action("GetAgendaItem")";
            //url = encodeURIComponent(url);
            $('#' + uniqDivId).load(url, itemAdded);*@
        }
        function itemAdded(responseText, textStatus, jqXHR) {
            var x = jqXHR;
            var id = jqXHR.id;
        }
        function addRoom(newRoomID)
        {
            //var tempDivId = new Date().getTime();
            var newDiv = $('<div class="beAgendaRoom" id="' + newRoomID + '"></div>');

            $(newDiv).droppable({ ////////////////////////////// Allows Drop of Topics/Meals from Agenda Palette
                //activeClass: "ui-state-default",
                hoverClass: "ui-state-hover",
                accept: ":not(.ui-sortable-helper)",
                drop: function (event, ui) {
                    $(this).find(".placeholder").remove();
                    var droppedID = ui.draggable.data('id');

                    addAgendaItem(this, ui.draggable);
                    //$("#accordion1").accordion('refresh');
                    $(this).accordion('refresh');
                }
            }).accordion({ ////////////////////////////////////// Allows Agenda Items to be collapsed/expanded
                collapsible: true,
                header: ".myHead"
            }).sortable({ /////////////////////////////////////// Allows Agenda Items to be sorted/arranged
                axis: "y",
                handle: ".myHead",
                stop: function (event, ui) {
                    // IE doesn't register the blur when sorting so trigger focusout handlers to remove .ui-state-focus
                    ui.item.children("h4").triggerHandler("focusout");

                    // Refresh accordion to handle new order
                    $(this).accordion("refresh");
                }
            });
            $(newDiv).appendTo('#beAgendaRooms');

            @*var opts = 'new { roomID: ' + newRoomID + '}';
            $('#' + newRoomID).load('@Url.Action("GetRoom", "Agenda"),' + opts, roomAdded);*@
            $('#' + newRoomID).load('@Url.Action("GetRoom", "Agenda")?roomID=' + newRoomID, roomAdded);

            //$('#beAgendaRooms').load('@(Url.Action("GetRoom", "Agenda", new {roomID = 53 }))')
        }
        function roomAdded(responseText, textStatus, jqXHR)
        {
            var x = jqXHR;

            //$(jqXHR).droppable({
            //    //activeClass: "ui-state-default",
            //    hoverClass: "ui-state-hover",
            //    accept: ":not(.ui-sortable-helper)",
            //    drop: function (event, ui) {
            //        $(this).find(".placeholder").remove();
            //        var droppedID = ui.draggable.data('id');

            //        addAgendaItem(this, ui.draggable);
            //        $("#accordion1").accordion('refresh');
            //    }
            //});
        }
        $(function () {
            $("#addRoom").click(function () {
                addRoom(53);
            });
            $("#button").click(function () {
                var options = {};
                $(".agendaPalette").toggle("slide", options, 500);
            });

            $("#agendaCategories").accordion({
                collapsible: true
            });
            $("#agendaCategories li").draggable({
                appendTo: "body",
                helper: "clone"
            });
            
            //$("#day1").droppable({
            //    //activeClass: "ui-state-default",
            //    hoverClass: "ui-state-hover",
            //    accept: ":not(.ui-sortable-helper)",
            //    drop: function (event, ui) {
            //        $(this).find(".placeholder").remove();
            //        var droppedID = ui.draggable.data('id');

            //        addAgendaItem(this, ui.draggable);
            //        $("#accordion1").accordion('refresh');
            //    }
            //});
            //$(".beAgendaRoomItems").accordion({
            //    collapsible: true,
            //    header: "> div > h4"
            //}).sortable({
            //    axis: "y",
            //    handle: "h4",
            //    stop: function (event, ui) {
            //        // IE doesn't register the blur when sorting
            //        // so trigger focusout handlers to remove .ui-state-focus
            //        ui.item.children("h4").triggerHandler("focusout");

            //        // Refresh accordion to handle new order
            //        $(this).accordion("refresh");
            //    }
            //});
            @foreach ( var room in Model.GetRooms() )
            {
                @:addRoom (@room.ID);
                //@Html.Action("GetRoom", new {roomID = room.ID })
            }
        }); // <-- $(function () {
    </script>
}